import type { Metadata } from "next";
import { routing } from "@/i18n/routing";
import { getSiteUrl } from "@/lib/site-url";

export const SITE_NAME = "OtherSide";

/** Branded 1200x630 card, generated by app/opengraph-image.tsx. */
export const DEFAULT_SHARE_IMAGE_PATH = "/opengraph-image";

/** "/products/x" + "ar" -> "/ar/products/x"; the default locale has no prefix. */
export function localizedPath(locale: string, path: string): string {
  const clean = path === "/" ? "" : path;
  if (locale === routing.defaultLocale) return clean || "/";
  return `/${locale}${clean}`;
}

export function absoluteUrl(path: string): string {
  return `${getSiteUrl()}${path}`;
}

/** Canonical URL (never carries ?color= / ?size=) plus en/ar/x-default alternates. */
export function pageAlternates(locale: string, path: string): Metadata["alternates"] {
  return {
    canonical: absoluteUrl(localizedPath(locale, path)),
    languages: {
      en: absoluteUrl(localizedPath("en", path)),
      ar: absoluteUrl(localizedPath("ar", path)),
      "x-default": absoluteUrl(localizedPath("en", path)),
    },
  };
}

/** A page-level openGraph replaces the layout's wholesale, so it must be complete. */
export function buildOpenGraph(input: {
  locale: string;
  path: string;
  title: string;
  description: string;
  image?: string | null;
}): NonNullable<Metadata["openGraph"]> {
  return {
    type: "website",
    siteName: SITE_NAME,
    locale: input.locale === "ar" ? "ar_EG" : "en_US",
    url: absoluteUrl(localizedPath(input.locale, input.path)),
    title: input.title,
    description: input.description,
    images: [
      input.image
        ? { url: input.image }
        : {
            url: absoluteUrl(DEFAULT_SHARE_IMAGE_PATH),
            width: 1200,
            height: 630,
            alt: "OtherSide — See the reality behind the veil.",
          },
    ],
  };
}

export function buildTwitter(input: {
  title: string;
  description: string;
  image?: string | null;
}): NonNullable<Metadata["twitter"]> {
  return {
    card: "summary_large_image",
    title: input.title,
    description: input.description,
    images: [input.image ?? absoluteUrl(DEFAULT_SHARE_IMAGE_PATH)],
  };
}

/** Keeps meta descriptions inside what search engines display (~155 chars). */
export function trimDescription(text: string, max = 155): string {
  const oneLine = text.replace(/\s+/g, " ").trim();
  if (oneLine.length <= max) return oneLine;
  const cut = oneLine.slice(0, max - 1);
  const lastSpace = cut.lastIndexOf(" ");
  return `${(lastSpace > 80 ? cut.slice(0, lastSpace) : cut).trimEnd()}…`;
}

export const NO_INDEX: Metadata["robots"] = { index: false, follow: false };

/** Product/blob image URLs may be relative (/uploads/...) in local dev. */
export function absoluteImageUrl(url: string): string {
  return /^https?:\/\//.test(url) ? url : absoluteUrl(url.startsWith("/") ? url : `/${url}`);
}
